// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjMffhg7DbH-dKmRLcvEVGqVMjUsN5NPY',
    appId: '1:688234500854:web:36f7a8017f971bd92ed2d7',
    messagingSenderId: '688234500854',
    projectId: 'playerhq-fe976',
    authDomain: 'playerhq-fe976.firebaseapp.com',
    storageBucket: 'playerhq-fe976.firebasestorage.app',
    measurementId: 'G-6WHCC8EKQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvQkMjUY3ZuXujeSO0dbCZVibJxtmwR6M',
    appId: '1:688234500854:android:18ce6f383a293a222ed2d7',
    messagingSenderId: '688234500854',
    projectId: 'playerhq-fe976',
    storageBucket: 'playerhq-fe976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4s_D_xPsv7Y6O8Y4QADEBillSy5vYOZE',
    appId: '1:688234500854:ios:88c00a6d498089702ed2d7',
    messagingSenderId: '688234500854',
    projectId: 'playerhq-fe976',
    storageBucket: 'playerhq-fe976.firebasestorage.app',
    iosBundleId: 'com.example.mobilePlayerhq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4s_D_xPsv7Y6O8Y4QADEBillSy5vYOZE',
    appId: '1:688234500854:ios:88c00a6d498089702ed2d7',
    messagingSenderId: '688234500854',
    projectId: 'playerhq-fe976',
    storageBucket: 'playerhq-fe976.firebasestorage.app',
    iosBundleId: 'com.example.mobilePlayerhq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjMffhg7DbH-dKmRLcvEVGqVMjUsN5NPY',
    appId: '1:688234500854:web:98015d3f3b344d202ed2d7',
    messagingSenderId: '688234500854',
    projectId: 'playerhq-fe976',
    authDomain: 'playerhq-fe976.firebaseapp.com',
    storageBucket: 'playerhq-fe976.firebasestorage.app',
    measurementId: 'G-ZW3M72KGWH',
  );
}
