name: mobile_playerhq
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.20.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  fl_chart: ^0.70.2
  url_launcher: ^6.1.5
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env